const WishlistActionTypes = {
	TOGGLE_WISHLIST_HIDDEN: "TOGGLE_WISHLIST_HIDDEN",
	ADD_ARTICLE: "ADD_ARTICLE",
	REMOVE_ARTICLE: "REMOVE_ARTICLE",
	CLEAR_WISHLIST: "CLEAR_WISHLIST",
};

export default WishlistActionTypes;
